apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.krancovia.io
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/cert-manager-webhook-gandi-ca-cert
spec:
  group: acme.krancovia.io
  version: v1alpha1
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    namespace: {{ .Release.Namespace }}
    name: cert-manager-webhook-gandi
