# This is the webhook server's own certificate.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-gandi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  issuerRef:
    name: cert-manager-webhook-gandi-ca
  commonName: "cert-manager-webhook-gandi.{{ .Release.Namespace }}"
  dnsNames:
  - cert-manager-webhook-gandi
  - cert-manager-webhook-gandi.{{ .Release.Namespace }}
  - cert-manager-webhook-gandi.{{ .Release.Namespace }}.svc
  duration: 8760h # 1 year
  secretName: cert-manager-webhook-gandi-cert
