# This gives the webhook server permission to read the
# extension-apiserver-authentication ConfigMap in the kube-system namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-gandi:extension-apiserver-authentication-reader
  namespace: kube-system
  labels:
    {{- include "labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: cert-manager-webhook-gandi
