apiVersion: v1
kind: Secret
metadata:
  name: gandi-access-token
  namespace: cert-manager
type: Opaque
stringData:
  token: $TOKEN
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gandi-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: $EMAIL
    privateKeySecretRef:
      name: letsencrypt-gandi-staging
    solvers:
    - dns01:
        webhook:
          groupName: acme.krancovia.io
          solverName: gandi
          config:
            apiKeySecretRef:
              name: gandi-access-token
              key: token
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-issuer-example
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-issuer-example
  namespace: cluster-issuer-example
spec:
  commonName: cluster-issuer-example.$ZONE
  dnsNames:
  - cluster-issuer-example.$ZONE
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-gandi-staging
  secretName: cluster-issuer-example-cert
