name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
    - main
    - release-*

permissions:
  contents: read

jobs:

  test-unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: "1.23.4"
    - name: Run unit tests
      run: make test-unit

  lint-go:
    runs-on: ubuntu-latest
    permissions:
      checks: write # Used to create checks (linting comments) on PRs
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: "1.23.4"
    - name: Run linter
      env:
        GO_LINT_ERROR_FORMAT: github-actions
      run: make lint-go

  lint-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Run linter
      run: make lint-chart

  check-docgen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install nodejs
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: "22.12.0"
    - name: Run Docgen
      run: make docgen
    - name: Check nothing has changed
      run: git diff --exit-code -- .

  build-image:
    needs: [test-unit, lint-go, lint-chart, check-docgen]
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
    - name: Build
      uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445 # v6.5.0
      with:
        platforms: linux/amd64,linux/arm64
        push: false

  # The full test suite can take quite some time to run, so everything else
  # must succeed before we're willing to execute these.
  test:
    needs: [build-image]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: "1.23.4"
    - name: Run full test suite
      env:
        TEST_ZONE: ${{ secrets.TEST_ZONE }}
        TEST_DNS_NAME: ${{ secrets.TEST_DNS_NAME }}
        GANDI_PAT: ${{ secrets.GANDI_PAT }}
      run: make test
    - name: Upload coverage reports
      uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
