name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
    - main
    - release-*

permissions:
  contents: read

jobs:

  test-unit:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.1-bookworm
    steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Run unit tests
      run: make test-unit

  lint-go:
    permissions:
      checks: write # Used to create checks (linting comments) on PRs
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.1-bookworm
    steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Run linter
      env:
        GO_LINT_ERROR_FORMAT: github-actions
      run: make lint-go

  lint-chart:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.1-bookworm
    steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Run linter
      run: make lint-charts

  build-image:
    needs: [test-unit, lint-go, lint-chart]
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
    - name: Build
      uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445 # v6.5.0
      with:
        platforms: linux/amd64,linux/arm64
        push: false

  # The full test suite can take quite some time to run, so everything else
  # must succeed before we're willing to execute these.
  test:
    needs: [build-image]
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.1-bookworm
    steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Run full test suite
      run: make test
    - name: Upload coverage reports
      uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
